#!/bin/sh

choice=$(printf "Shutdown\nReboot" | dmenu -c -l 5 -i -p "Choose: ")

confirm() {
	__sd=$(printf "Yes\nNo" | dmenu -c -l 5 -i -p "Are you sure you want to $1?")
	if [ "$__sd" = "Yes" ]; then
		echo "none" > /home/aditya/suckless/scripts/xsetCommand
        $($2)
	fi
}

[[ "$choice" == "Shutdown" ]] && confirm "Shutdown" poweroff

[[ "$choice" == "Reboot"  ]] && confirm "Reboot" reboot
