source $HOME/.config/nvim/plugins.vim
lua require('impatient')
source $HOME/.config/nvim/settings.vim
source $HOME/.config/nvim/mappings.vim
luafile $HOME/.config/nvim/lsp/servers.lua
luafile $HOME/.config/nvim/plugconf/telescope.lua
luafile $HOME/.config/nvim/plugconf/treesitter.lua
luafile $HOME/.config/nvim/plugconf/compe.lua
luafile $HOME/.config/nvim/plugconf/lualine.lua
luafile $HOME/.config/nvim/plugconf/luasnips.lua
