#!/bin/sh
#this is Luke's Script I have just made some changes like removing the arguments part
chosenEmoji=$(cut -d ';' -f1 ~/scripts/emojiList | dmenu -i -F -l 10 | sed "s/ .*//") &&
[ -z "$chosenEmoji" ] && exit

printf "$chosenEmoji" | xclip -selection clipboard
notify-send "'$chosenEmoji' copied to clipboard." &
