#!/bin/sh
__clr_="$RED_COLOR"
__CFILE_="$HOME/scripts/lastPlayedSong"
__cmd=__current_song__cmd
__current_song__cmd() {
    cat "$__CFILE_"
}

____mpc() {
    __clr_="$ORANGE_COLOR"
    printf "^c$__clr_^  ^c$LIGHT_BLUE_COLOR^%s -^c$GREEN_COLOR^ %s^c$WHITE_COLOR^" "$(mpc current -f %artist%)" "$(mpc current -f %title%)"
    printf "^c$__clr_^  ^c$LIGHT_BLUE_COLOR^%s -^c$GREEN_COLOR^ %s^c$WHITE_COLOR^" "$(mpc current -f %artist%)" "$(mpc current -f %title%)" > "$__CFILE_"
}

____spot() {
    ___sp_artist="$(playerctl -p spotify metadata title)"
    ___sp_title="$(playerctl -p spotify metadata artist)"
    ____spfun() {
        printf "^c#1ed760^  ^c#b2e4ff^%s -^c#63ff8a^ %s^c#ffffff^" "$___sp_artist" "$___sp_title"
        printf "^c#1ed760^  ^c#b2e4ff^%s -^c#63ff8a^ %s^c#ffffff^" "$___sp_artist" "$___sp_title" > "$__CFILE_"
    }
    [[ "$___sp_artist" == "" ]] && [[ "$___sp_title" == ""  ]] && cat "$__CFILE_" || ____spfun

}

[[ "$(mpc status | sed -n 2p | awk '{print $1;}')" == "[playing]" ]] && ____mpc || ____spot
