#!/bin/sh
fileName=$(date '+%b%d%a%I%M%S%p')
directoryName=$(cat /home/aditya/scripts/directoryfile)

part() {
    escrotum -s $directoryName/$fileName.png &&
    notify-send -t 1200 -i /D/Downloads/screenshot.png "Screenshot Captured" "Destination: $directoryName\nFile Name: $fileName"
    printf "$directoryName/$fileName.png" | xclip -selection clipboard
}

full() {
    ffmpeg -f x11grab -video_size 1920x1080 -i $DISPLAY -vframes 1 $directoryName/$fileName.png && notify-send -t 1200 -i /D/Downloads/screenshot.png "Screenshot Captured" "Destination: $directoryName\nFile Name: $fileName"
}

[[ "$1" == "part" ]] && part || full
