#!/bin/zsh

TODO_FILE="$HOME/.cache/todofile"

! [[ -e $TODO_FILE ]] && touch "$TODO_FILE"

local __dmenucmd() {
    printf "dmenu -i -f -c -l 10"
}

local selection="$(cat "$TODO_FILE" | $(__dmenucmd))"

[[ "$selection" == "" ]] && exit

TODO_SIZE="$(wc -l $TODO_FILE | awk '{print $1}')"
NEXT_SIZE=$((TODO_SIZE + 1))

grep -q "add " <<< "$selection" &&
    echo "${selection/add/"$NEXT_SIZE"}" >> "$TODO_FILE" ||
    sed -i "/$selection/d" "$TODO_FILE"
