#!/bin/bash

if [[ "$1" == "-m" ]]; then
	st=$2
	transmission-remote --add "$st" &&
		notify-send "Torrent Added 🧲" "$st"
else
	st=$(ls /D/Downloads/*.torrent | dmenu -i -p "Choose Torrent 🧲" -l 10)
	if [[ "$st" != "" ]]; then
		transmission-remote --add "$st" &&
			notify-send "Torrent Added 🧲" "$st"
	fi
fi

