[colors]
draw_bold_text_with_bright_colors = false

# Colors (Vscode)

[colors.primary]
background = "0x202124"
foreground = "0xD4D4D4"

[colors.normal]
black = "0x1E1E1E"
red = "0xF44747"
green = "0x608B4E"
yellow = "0xD7BA7D"
blue = "0x569CD6"
magenta = "0xC586C0"
cyan = "0x9CDCFE"
white = "0xD4D4D4"

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.normal]
family = "Sauce Code Pro Nerd Font"

[shell]
program = "/bin/zsh"

[window]
opacity = 1
