[colors]
draw_bold_text_with_bright_colors = false

# Colors (Solarized Dark)

# Default colors
[colors.primary]
background = '#002b36'
foreground = '#839496'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#002b36'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 10.5

[font.normal]
family = "Sauce Code Pro Nerd Font"

[shell]
program = "/bin/zsh"

[window]
opacity = 1
