#!/bin/bash

SAVEIFS=$IFS   # Save current IFS
IFS=$'\n'      # Change IFS to new line
IFS=$SAVEIFS   # Restore IFS

bssid=$(nmcli d wifi list | sed -n '1!p' | cut -b 9- | dmenu -l 5 -p "Select BSSID >  "| awk '{print $1}')
if [[ "$bssid" != "" ]]; then
	nmcli d wifi connect "$bssid" ||
		nmcli d wifi connect "$bssid" password "$(printf "" | dmenu -p "Enter the Password" -l 5)" && notify-send "Connected !" "succesfully connected to $bssid" ||
			notify-send "Failed To Connect" -u critical
fi
